version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgAdmin@4
      POSTGRES_DB: bookstoredb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  backend:
    image: anuvabchakraborty/flask-backend:latest
    container_name: flask-backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - backend

  frontend:
    image: anuvabchakraborty/react-frontend:latest
    container_name: react-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
    driver: local
